class ChiveException(Exception):
    pass


class RetryTask(ChiveException):
    pass
